{% set name = "jupyterlab_rise" %}
{% set version = "0.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3c401ad1abcfd7a3189d8fed997b059a59423e9fd8bec763b392ded4f5c05e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.4.0
    - jupyterlab >=4.0.0,<5.0.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyterlab >=4.0.0,<5.0.0

test:
  imports:
    - jupyterlab_rise
  requires:
    - pip
  commands:
    - pip check
    - python -m jupyterlab.browser_check --no-browser-test

about:
  home: https://github.com/jupyterlab-contrib/rise
  summary: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
