{% set name = "jupyterlab_rise" %}
{% set version = "0.43.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 264ec00e2cb5cc68e2042a054eea2d42925f47f36d883eba9c475b6dd2fe87d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.4.0
    - jupyterlab >=4.0.0,<5.0.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyterlab >=4.0.0,<5.0.0

test:
  imports:
    - jupyterlab_rise
  requires:
    - pip
  commands:
    - pip check
    - python -m jupyterlab.browser_check --no-browser-test

about:
  home: https://github.com/jupyterlab-contrib/rise
  summary: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
